### ISSUE TITLE
crashing whenever i change the range to the value 2

### ISSUE THREAD

**Issue by kakazander** [kkllffaa/meteor-litematica-printer#28]
minecraft fabric version: 1.20.4 
meteor: 0.5.6

Whenever I get close to the schematic, my game crashes. (With the value 1, it doesn't build, so I have to put it up to the value 2. Then bam, it instantly crashes)

**Comment by Tenico05** [comment]
Time: 2024-03-28 20:18:03
Description: Unexpected error

java.lang.NoClassDefFoundError: baritone/api/utils/BetterBlockPos
	at com.kkllffaa.meteor_litematica_printer.Printer.lambda$onTick$3(Printer.java:257)
	at meteordevelopment.meteorclient.utils.world.BlockIterator.onTick(BlockIterator.java:66)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
	at net.minecraft.class_310.handler$blm000$meteor-client$onPreTick(class_310.java:9329)
	at net.minecraft.class_310.method_1574(class_310.java)
	at net.minecraft.class_310.method_1523(class_310.java:1289)
	at net.minecraft.class_310.method_1514(class_310.java:888)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.ClassNotFoundException: baritone.api.utils.BetterBlockPos
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 12 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.kkllffaa.meteor_litematica_printer.Printer.lambda$onTick$3(Printer.java:257)
	at meteordevelopment.meteorclient.utils.world.BlockIterator.onTick(BlockIterator.java:66)
	at meteordevelopment.orbit.listeners.LambdaListener.call(LambdaListener.java:83)
	at meteordevelopment.orbit.EventBus.post(EventBus.java:53)
	at net.minecraft.class_310.handler$blm000$meteor-client$onPreTick(class_310.java:9329)

-- Uptime --
Details:
	JVM uptime: 42.539s
	Wall uptime: 26.434s
	High-res time: 24.460s
	Client ticks: 241 ticks / 12.050s
Stacktrace:
	at net.minecraft.class_310.method_1587(class_310.java:2564)
	at net.minecraft.class_310.method_54580(class_310.java:995)
	at net.minecraft.class_310.method_1514(class_310.java:911)
	at net.minecraft.client.main.Main.main(Main.java:265)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by kkllffaa** [comment]
Since meteor 0.5.6 they don't include baritone by default so you need to download and install it manually from meteor website, i added it as dependency now so it crashes at startup and displays better error.

**Comment by Tenico05** [comment]
Thank you for clarifying, i was using the normal baritone :D
